@Library('CommonLib') _
pipeline {
    agent any
    
    parameters {
        string(name: 'Docker_F_Tag', defaultValue: '', description: 'The Frontend Docker tag of the image built by the CI job')
        string(name: 'Docker_B_Tag', defaultValue: '', description: 'The Backend Docker tag of the image built by the CI job')
    }

    stages {
        stage("Workspace cleanup"){
            steps{
                script{
                    cleanWs()
                }
            }
        }
        
        stage('Git: Code Checkout') {
            steps {
                script{
                    code_checkout("https://github.com/mrvanny/the-traveler.git","main")
                }
            }
        }
        
        stage('Verify: Docker Image Tags') {
            steps {
                script{
                    echo "Docker_F_Tag: ${params.Docker_F_Tag}"
                    echo "Docker_B_Tag: ${params.Docker_B_Tag}"
                }
            }
        }
        
        
        stage("Update: Kubernetes manifests"){
            steps{
                script{
                    dir('kubernetes'){
                        sh """
                            sed -i "s|image: .*thetraveler-backend-beta:.*|image: theroot77/thetraveler-backend-beta:${params.Docker_B_Tag}|g" backend.yaml
                        """
                    }
                    
                    dir('kubernetes'){
                        sh """
                            sed -i "s|image: .*thetraveler-frontend-beta:.*|image: theroot77/thetraveler-frontend-beta:${params.Docker_F_Tag}|g" frontend.yaml
                            """
                    }
                    
                }
            }
        }
        
        stage("Git: Code update and push to GitHub"){
            steps{
                script{
                    withCredentials([gitUsernamePassword(credentialsId: 'Github-cred', gitToolName: 'Default')]) {
                        sh '''
                        echo "Checking repository status: "
                        git status
                    
                        echo "Adding changes to git: "
                        git add .
                        
                        echo "Commiting changes: "
                        git commit -m "Updated environment variables"
                        
                        echo "Pushing changes to github: "
                        git push https://github.com/mrvanny/the-traveler.git main
                    '''
                    }
                }
            }
        }
    }
    post {

    success {
        script {
            slackSend(
                color: 'good',
                message: """
                        ✅ *Deployment Successful*
                        
                        Project: ${env.JOB_NAME}
                        Build Number: ${env.BUILD_NUMBER}
                        Build URL: ${env.BUILD_URL}
                        """
            )
        }
    }

    failure {
        script {
            slackSend(
                color: 'danger',
                message: """
                        ❌ *Build Failed*
                        
                        Project: ${env.JOB_NAME}
                        Build Number: ${env.BUILD_NUMBER}
                        Build URL: ${env.BUILD_URL}
                        """
            )
        }
    }
}
}
